version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run:
                name:  ðŸ“¦ Install packages
                command: yarn install
            - run:
                name:  ðŸ§¹ Linting
                command: yarn lint
            - run:
                name:  ðŸ§ª Testing
                command: yarn test
  publish:
    executor:
      name: node/default
    steps:
      - checkout
      - run:
          name:  ðŸ“¦ Install packages
          command: yarn install
      - run:
          name:  ðŸš§ Building
          command: yarn build
      - run: 
          name: ðŸš€ Publish to Github Package
          command: yarn ci:publish
          environment: 
            GH_TOKEN: echo ${GH_TOKEN}
            NPM_TOKEN: echo ${NPM_TOKEN}

workflows:
    build-and-test:
      jobs:
        - build-and-test
        - publish: 
            requires:
              - build-and-test
            filters:
              branches:
                only: master